#!/usr/bin/env sh
set -e

export SECRETKEY=`openssl rand -hex 32`
export UPGRADEKEY=`openssl rand -hex 8`

if [ ! -d /var/www/html/w ] ; then
    mv /w /var/www/html/
fi 

envsubst '$DBserver,$DBname,$DBuser,$DBpassword,$Sitename,$MetaNamespace,$Server,$SECRETKEY,$UPGRADEKEY' < /LocalSettings.php.template > /var/www/html/w/LocalSettings.php

cp /fail2banlog.php /var/www/html/w/extensions/fail2banlog.php

exec "$@"

